services:
  payment-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: payment-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspaces/payment-gateway/
    tty: true

  ngrok:
    image: ngrok/ngrok:alpine
    command: http host.docker.internal:3000
    ports:
      - 4040:4040
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
